### ISSUE TITLE
[Manjaro Linux] Crash on AppImage-Startup

### ISSUE THREAD

**Issue by datenbrei** [peerlinks/peerlinks-desktop#38]
Hi. The latest 3.9.4 AppImage crashes on Manjaro-Linux:
~~~
./PeerLinks-3.9.4_7946d4b1f445d611636e0fae628594d1.AppImage 
qt5ct: using qt5ct plugin
A JavaScript error occurred in the main process
Uncaught Exception:
/tmp/.mount_PeerLihZVFtX/resources/app.asar/src/electron/main.js:1
Error: /tmp/.org.chromium.Chromium.BAK9qZ: UngÃ¼ltiger ELF-Header
    at process.func (electron/js2c/asar.js:138:31)
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:138:31)
    at Object.func [as .node] (electron/js2c/asar.js:147:18)
~~~
My Desktop-System:
Linux acer 5.3.8-3-MANJARO #1 SMP PREEMPT Sun Nov 3 14:19:23 UTC 2019 x86_64 GNU/Linux

**Comment by indutny** [comment]
Hello!

Sorry to hear this.

Did it work at all before?

**Comment by indutny** [comment]
Reported to electron-builder: https://github.com/electron-userland/electron-builder/issues/4465

**Comment by datenbrei** [comment]
Well, version 3.9.6 is running well now on 5.4.6-2-MANJARO x86_64 GNU/Linux.
